// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/_locales/en/messages.json"
    | "/_locales/vi/messages.json"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icons/128.png"
    | "/icons/128.png"
    | "/icons/16.png"
    | "/icons/16.png"
    | "/icons/32.png"
    | "/icons/32.png"
    | "/icons/48.png"
    | "/icons/48.png"
    | "/polar-bear-3-svgrepo-com.svg"
    | "/popup-bak.html"
    | "/sidebar.js"
    | "/sidepanel.html"
    | "/types.js"
    | "/wxt.svg"
    | "/zsm.jpg"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
